### ISSUE TITLE
TypeError: make() takes exactly 3 arguments (26 given)

### ISSUE THREAD

**Issue by MountainLogic** [myriadrf/gr-limesdr#33]
Just installed the MacPort and that went well.  I'm working from the example FM receiver with changes to the gui for QT.  Now I'm seeing the following at compile time 

`
Generating: '/opt/local/share/gnuradio/examples/gr-limesdr/top_block.py'

Executing: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u /opt/local/share/gnuradio/examples/gr-limesdr/top_block.py

Traceback (most recent call last):
  File "/opt/local/share/gnuradio/examples/gr-limesdr/top_block.py", line 235, in <module>
    main()
  File "/opt/local/share/gnuradio/examples/gr-limesdr/top_block.py", line 223, in main
    tb = top_block_cls()
  File "/opt/local/share/gnuradio/examples/gr-limesdr/top_block.py", line 161, in __init__
    60)
TypeError: make() takes exactly 3 arguments (26 given)

>>> Done (return code 1)
`
line 161 points to:

`

        self.limesdr_source_0_0 = limesdr.source(0,
        			 2,
        			 1,
        			 0,
        			 0,
        			 '',
        			 100.1e6,
        			 samp_rate,
        			 0,
        			 0,
        			 2.6e6,
        			 0,
        			 2.6e6,
        			 1,
        			 1,
        			 1,
        			 0,
        			 1.5e6,
        			 0,
        			 1.5e6,
        			 0,
        			 100e3,
        			 0,
        			 100e3,
        			 60,
        			 60)
        self.blocks_multiply_const_vxx_0_1 = blocks.multiply_const_vff((volume, ))
        self.audio_sink_0_0 = audio.sink(48000, '', True)
        self.analog_wfm_rcv_0_1 = analog.wfm_rcv(
        	quad_rate=480e3,
        	audio_decimation=10,
        )
`

This is clearly not what is show in the documentation tab:
`limesdr_source
make(std::string serial, int channel_mode, std::string const & filename) -> source_sptr
        Return a shared_ptr to a new instance of source.
        To avoid accidental use of raw pointers, source's constructor is private. limesdr::source::make is the public interface for creating new instances.
        Params: (serial, channel_mode, filename)
`

I suspect that I may have some detritus left over from previous installs with the brew package manager?  Could this be a version 1 vs 2 issue?

**Comment by MountainLogic** [comment]
Looks like brew left the old v 1.0 xml file in 
/opt/local/share/gnuradio/grc/blocks
