### ISSUE TITLE
Support for GNURadio 3.9.x

### ISSUE THREAD

**Issue by eggelene** [myriadrf/gr-limesdr#75]
I tried to use the latest LimeSDR ( from ppa:myriadrf/gnuradio) sink in GNURadio 3.9.1.0. But it seems that the sink is not compatible with latest GNURadio release. 

Is there any plan to add LimeSDR support for GNURadio 3.9.1.0 ? Preferable installable through the ppa:myriadrf/gnuradio.

**Comment by Phil67ago** [comment]
I have the same question.
gr-3.9 has replaced SWIG with Pybind11.
I made some efforts following this guid but I'm kind of lost when it comes to adding binding at step 4.
Call gr_modtool bind for each block in your OOT.
https://wiki.gnuradio.org/index.php/GNU_Radio_3.9_OOT_Module_Porting_Guide

It would be nice if someone created a branch gr-3.9 and made the basic porting steps and CMake stuff
as a starting point.

**Comment by chrisjohgorman** [comment]
I have tried to migrate this module to gnuradio 3.9.  My attempt can be found at https://github.com/chrisjohgorman/gr-limesdr.git .
I don't currently own a limesdr to test my modifications out on, but it builds on my system and installs.  I can import the module from python.  If you find bugs, and I'm sure there are some (rfe boards may not be properly supported.)  Please email me and I will try to hunt them down.

**Comment by Phil67ago** [comment]
Ok Fine! I will give it a try. It may take me a couple of weeks before I can dig into it...

**Comment by chrisjohgorman** [comment]
@Phil67ago please re download gr-limesdr.git from my repository.  I forgot to do a git add to add the new files and as a result my github code was incomplete.  I have tested it and it _should_ work now.  Sorry for the omission.

**Comment by NZSmartie** [comment]
Hey @chrisjohgorman I gave your fork a go, I fixed a few things and created the needed python bindings.
I can confirm that my LimeSDR-mini now works with the source module in GNU Radio 3.9, however I have not tested the sink, yet. As I don't have a project ready to go.

**Comment by dsgibbons** [comment]
I tested @chrisjohgorman fork - seems to work well for LimeSDR-USB. Thanks for doing this.

**Comment by wkazubski** [comment]
Please bump the library version declared in CmakeFile.txt. Last release for GR-3.7 was anounced as 2.0, last snapshot in 3.8 branch has  library version 3.1.5, so version for GR-3.9 should be 3.2.0 or even 4.0.0 to avoid confusion during upgrade.

**Comment by chrisjohgorman** [comment]
Hi Wojciech,

If I understand you, I need to update the VERSION_MAJOR, VERSION_API and
VERSION_ABI to something greater than 3.1.5.  I believe it should be 3.2.0,
but I don't know what lime microsystems would prefer.  I'm on my way to
change it and will set it to 3.2.0.  I hope this helps.

Take care.

Chris

**Comment by wkazubski** [comment]
Yes. . If there is no major changes, version 3.2.0 is OK. I suppose that version 1.0.0 is a default setting in Cmake. Leaving it nay make some confusion for package managers in various Linux distributions. For example openSUSE / SUSE Linux package libries separatedly and require library package to have the same version as the library executable  inside.

Wojciech

**Comment by chrisjohgorman** [comment]
Yes. 1.0.0 is the default setting of gr_modtool which is used to make the
module.  Good to hear that 3.2.0 is OK.  Take care.

Chris

**Comment by cweickhmann** [comment]
Quick feedback using a Gnuradio 3.10 and a LimeSDR USB. Initialisation seems to work well, but module `rfe` is not found.

```
---------------------------------------------------------------
LimeSuite Source (RX) info

##################
Connecting to device
##################
LimeSuite version: 23.11.0+dfsg-3
gr-limesdr version: 2.2.7
##################
Device list:
Nr.:0 device:LimeSDR-USB, media=USB 2.0, module=FX3, addr=1d50:6108, serial=0009081C05C4272F
##################
INFO: device_handler::open_device(): no serial number. Using first device in the list.
Use "LimeUtil --find" in terminal to find prefered device serial.
Reference clock 30,72 MHz
Using device: LimeSDR-USB(0009081C05C4272F) GW: 2.23 FW: 4
##################

INFO: device_handler::enable_channels(): SISO CH0 set for device number 0.
SISO CH0 set for device number 0.
INFO: device_handler::set_samp_rate(): set sampling rate: 2 MS/s.
INFO: device_handler::set_rf_freq(): RF frequency set [RX]: 1090 MHz.
INFO: device_handler::set_analog_filter(): RX LPF configured
INFO: device_handler::set_digital_filter(): GFIR LPF cannot be set to the requested bandwidth
digital filter CH0 [RX]: 2 MHz.
INFO: device_handler::set_gain(): set gain [RX] CH0: 10 dB.
INFO: device_handler::set_antenna(): CH0 antenna set [RX]: LNAL.
INFO: device_handler::calibrate(): Rx calibration finished
Traceback (most recent call last):
  File "/home/c/Software/gr-adsb/examples/adsb_rx.py", line 255, in <module>
    main()
    ~~~~^^
  File "/home/c/Software/gr-adsb/examples/adsb_rx.py", line 232, in main
    tb = top_block_cls()
  File "/home/c/Software/gr-adsb/examples/adsb_rx.py", line 151, in __init__
    self.limesdr_rfe_0 = limesdr.rfe(0,
                         ^^^^^^^^^^^
AttributeError: module 'limesdr' has no attribute 'rfe'
libusb: warning [libusb_exit] device 1.6 still referenced
libusb: warning [libusb_exit] device 1.2 still referenced
libusb: warning [libusb_exit] device 1.1 still referenced
libusb: warning [libusb_exit] application left some devices open

>>> Done (return code 1)
```

Any idea where to look to fix this?

**Comment by chrisjohgorman** [comment]
Hi @cweickhmann,

I don't have any limesdr hardware to test your error with.  My personal
experience with this was to simply port gnuradio 3.8 code to 3.9.  I am
surprised that it has worked as long as it has.  Unfortunately, I don't
know where to look to fix this.  Perhaps someone has a more recent
gr-limesdr port?

Best of luck,

Chris

**Comment by rjonaitis** [comment]
Seems RFE module is disabled by default: https://github.com/myriadrf/gr-limesdr/blob/244c6bf4f1cb52a8b4d27240d7a4c88c9542cbbb/CMakeLists.txt#L165
you need to set option `-DENABLE_RFE=on` when configuring cmake

**Comment by cweickhmann** [comment]
Thanks, @chrisjohgorman & @rjonaitis!
I'll check if enabling RFE helps me out and let you know.
